name: Sentry action
on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
      
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: production
        sourcemaps: './dist/sentry'
        version_prefix: 'sentry@'
        version: ${{ steps.package-version.outputs.current-version}}
