name: Sentry action
on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
  sentry:
   runs-on: ubuntu-latest
   needs: [start]
   
   steps:
        
    - uses: actions/checkout@v2
    
    - name: Move
      shell: bash
      run: |
        mkdir test2
        mv ./test/sentry/*.map ./test2
        mv ./test/sentry/*.js ./test2
        
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: production
        sourcemaps: './test2'
        version_prefix: 'sentry@'
        version: '2.0.0'
        url_prefix: '~'
