name: Sentry action
on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest

    
  sentry:
   runs-on: ubuntu-latest
   needs: [start]
   
   steps:
        
    - uses: actions/checkout@v2
        
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: production
        sourcemaps: './test/sentry/'
        version_prefix: 'sentry@'
        version: '2.0.0'
        url_prefix: '~'
